name: Run Telegram Bot
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: timeout 270 node index.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          GEMINI_MODEL: gemini-1.5-flash-latest


